# Valori di Autosubmit
HPCROOTDIR=%HPCROOTDIR%
PROJDIR=%PROJDIR%
START_DATE=%CHUNK_START_DATE%     # YYYYMMDD
END_DATE=%CHUNK_END_DATE%
MEMBER=%MEMBER%


START_ISO="${START_DATE:0:4}-${START_DATE:4:2}-${START_DATE:6:2}"
MEMBER_NUM="${MEMBER#fc}"

INDIR="${HPCROOTDIR}/DATA/${START_DATE}/${MEMBER}"
INFER_FILE="${INDIR}/${START_ISO}_r${MEMBER_NUM}_infer.nc"
FINAL_OUTDIR="${HPCROOTDIR}/INFERRED"
mkdir -p "${FINAL_OUTDIR}"
FINAL_FILE="${FINAL_OUTDIR}/${START_ISO}_r${MEMBER_NUM}_infer.nc"

cp "${INFER_FILE}" "${FINAL_FILE}"
rm "${INFER_FILE}"