#!/bin/bash
# PREPARE-ICS-CMIP6
set -xuve

# Autofilled values by Autosubmit:
HPCROOTDIR=%HPCROOTDIR%
PROJDIR=%PROJDIR%
START_DATE=%CHUNK_START_DATE%     # Format: YYYYMMDD
END_DATE=%CHUNK_END_DATE%         # Same format as the chunk
GIT_ORIGIN=%GIT.PROJECT_ORIGIN%
PROJECT_BRANCH=%GIT.PROJECT_BRANCH%

cd $HPCROOTDIR
git clone $GIT_ORIGIN -b $PROJECT_BRANCH git_project